<?php
global $rz_b2_options;
$arMenuOptions = array(
	$rz_b2_options["block_home-main-slider"],
       'hits' =>$rz_b2_options["block_main-menu-elem"],
	$rz_b2_options["block_menu_count"],
	$rz_b2_options["menu-hits-position"],
	$rz_b2_options["menu-show-icons"]
);
?>
<?
$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"big_slider",
	array(
		"IBLOCK_TYPE" => "services",
		"IBLOCK_ID" => "4",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"NEWS_COUNT" => "5",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "DETAIL_PICTURE",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "LINK",
			1 => "",
		),
		"CHECK_DATES" => "Y",
		"CACHE_FILTER" => "N",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_STATUS_404" => "N",
		"RESIZER_SET_1200" => "10",
		"RESIZER_SET_991" => "10",
		"USE_RESIZER_SET_FROM_1200" => "N",
		"RESIZER_SET_FROM_1200" => "",
		"SORT_BY1" => "sort",
		"SORT_ORDER1" => "asc",
		"SORT_BY2" => "id",
		"SORT_ORDER2" => "desc",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"SLIDER_WIDTH" => $rz_b2_options["big-slider-width"],
		"MENU_CATALOG" => ($rz_b2_options["menu-catalog"]=="side"?$arMenuOptions:false),
		"bs_height" => $rz_b2_options["bs_height"],
		"bs_media_h-align" => $rz_b2_options["bs_media_h-align"],
		"bs_media_limits_bottom" => $rz_b2_options["bs_media_limits_bottom"],
		"bs_media_limits_left" => $rz_b2_options["bs_media_limits_left"],
		"bs_media_limits_right" => $rz_b2_options["bs_media_limits_right"],
		"bs_media_limits_top" => $rz_b2_options["bs_media_limits_top"],
		"bs_media_v-align" => $rz_b2_options["bs_media_v-align"],
		"bs_text_h-align" => $rz_b2_options["bs_text_h-align"],
		"bs_text_limits_bottom" => $rz_b2_options["bs_text_limits_bottom"],
		"bs_text_limits_left" => $rz_b2_options["bs_text_limits_left"],
		"bs_text_limits_right" => $rz_b2_options["bs_text_limits_right"],
		"bs_text_limits_top" => $rz_b2_options["bs_text_limits_top"],
		"bs_text_text-align" => $rz_b2_options["bs_text_text-align"],
		"bs_text_v-align" => $rz_b2_options["bs_text_v-align"],
        'SLIDER_ORDER' => $rz_b2_options["order-sBigSlider"],
        'SLIDER_ORDER' => $rz_b2_options["order-sBigSlider"],
	),
	false
);
?>
