<?php
if(\Bitrix\Main\Loader::includeModule('sib.core')){
	\Sib\Core\Regions::updateRegionStores();
}
$APPLICATION->IncludeComponent(
    "bitrix:catalog.section",
    "sib_basket",
    array(
        "IBLOCK_TYPE" => "catalog",
        "IS_SMARTPHONE_ITEM" => $isSmartphoneItem ? 'Y' : 'N',
        "IBLOCK_ID" => "6",
        "SECTION_ID" => "",
        "SECTION_CODE" => "",
        "INCLUDE_SUBSECTIONS" => "Y",
        "SHOW_ALL_WO_SECTION" => "Y",
        "HIDE_NOTAVAILABLE" => "Y",
        "HIDE_WITHOUTPICTURE" => "Y",
        "RESIZER_SET_BIG" => "3",
        "ELEMENT_SORT_FIELD" => "name",
        "ELEMENT_SORT_ORDER" => "asc",
        "LIST_PRICE_SORT" => "CATALOG_PRICE_1",
        "SHOW_ELEMENT" => "N",
        "OFFERS_FIELD_CODE" => ",",
        "OFFERS_PROPERTY_CODE" => ",",
        "OFFERS_SORT_FIELD" => "sort",
        "OFFERS_SORT_ORDER" => "asc",
        "PAGE_ELEMENT_COUNT" => "36",
        "LINE_ELEMENT_COUNT" => "4",
        "ACTION_VARIABLE" => "action",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "PRICE_CODE" => $_SESSION["VREGIONS_REGION"]["PRICE_CODE"],
        "STORES" => $_SESSION["VREGIONS_REGION"]["ID_SKLADA"],
        "USE_PRICE_COUNT" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "BASKET_URL" => "/personal/cart/",
        "PRICE_VAT_INCLUDE" => "Y",
        "USE_PRODUCT_QUANTITY" => "Y",
        "HIDE_BUY_IF_PROPS" => "N",
        "CONVERT_CURRENCY" => "Y",
        "OFFERS_CART_PROPERTIES" => "",
        "CACHE_TYPE" => "A",
        "CACHE_TIME" => "86400",
        "CACHE_GROUPS" => "Y",
        "META_KEYWORDS" => "-",
        "META_DESCRIPTION" => "-",
        "BROWSER_TITLE" => "-",
        "ADD_SECTIONS_CHAIN" => "N",
        "DISPLAY_COMPARE" => "Y",
        "OFFER_TREE_PROPS" => array(
        ),
        "INCLUDE_JQUERY" => "Y",
        "FILTER_NAME" => "arrBasketFilter",
        "USE_FILTER" => "Y",
    )
);