<?
$PERM["kredit"]["*"]="D";
$PERM["kredit"]["6"]="X";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["9"]="T_8";
$PERM["personal"]["7"]="W";
$PERM["personal"]["6"]="W";
$PERM["catalog"]["7"]="W";
$PERM["catalog"]["6"]="W";
$PERM["news"]["7"]="W";
$PERM["news"]["6"]="W";
$PERM["about"]["7"]="W";
$PERM["about"]["6"]="W";
$PERM["index.php"]["7"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
$PERM["order_export"]["7"]="W";
?>