<?
$iblockId = 50;
if($_SERVER['SERVER_NAME'] == 'dev.sibdroid.ru'){
    $iblockId = 51;
}
$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "sib_flamp",
    array(
        "IBLOCK_TYPE" => "references",
        "IBLOCK_ID" => $iblockId,
        "RESIZER_SET" => "36",
        "FILTER_NAME" => "",
        "FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "PROPERTY_CODE" => array(
            0 => "AUTHOR_NAME",
            1 => "AUTHOR_RATING",
            2 => "REVIEW_RATING",
            3 => "REVIEW_LINK",
        ),
        "CACHE_TYPE" => "A",
        "CACHE_TIME" => "36000000",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "ADD_SECTIONS_CHAIN" => "N",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "PARENT_SECTION" => "",
        "PARENT_SECTION_CODE" => "",
        "INCLUDE_SUBSECTIONS" => "Y",
        "AJAX_OPTION_ADDITIONAL" => "",
        "COMPONENT_TEMPLATE" => "sib_flamp",
        "NEWS_COUNT" => "20",
        "CHECK_DATES" => "Y",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "SORT_BY1" => "",
        "SORT_ORDER1" => "",
        "SORT_BY2" => "",
        "SORT_ORDER2" => "",
        "DETAIL_URL" => "",
        "PREVIEW_TRUNCATE_LEN" => "",
        "ACTIVE_DATE_FORMAT" => "",
        "SET_BROWSER_TITLE" => "N",
        "SET_META_KEYWORDS" => "Y",
        "SET_META_DESCRIPTION" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "STRICT_SECTION_CHECK" => "N",
        "PAGER_TEMPLATE" => "",
        "DISPLAY_TOP_PAGER" => "",
        "DISPLAY_BOTTOM_PAGER" => "",
        "PAGER_TITLE" => "",
        "PAGER_SHOW_ALWAYS" => "",
        "PAGER_DESC_NUMBERING" => "",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "",
        "PAGER_SHOW_ALL" => "",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "SHOW_404" => "N",
        "MESSAGE_404" => "",
        "LINK_ALL_ITEMS_FLAMP" => "https://novosibirsk.flamp.ru/firm/sibdroid_internet_magazin_smartfonov-141266769974840#reviews",
        "RESIZER_SET" => "38",
        "REVIEWS_COUNT" => "219",
        "SHOP_RATING" => "5",
    ),
    false
);?>
